# Generated by Django 5.1.1 on 2026-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.DeleteModel(
            name='ListВepartment',
        ),
    ]
