# Generated by Django 5.1.1 on 2026-04-27 14:56

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyConverterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_status_document', models.BooleanField(default=False, verbose_name='Инструкция')),
                ('is_status_spare_part', models.BooleanField(default=False, verbose_name='ЗИП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=100, verbose_name='Частотный преобразователь')),
                ('is_status_programm', models.BooleanField(verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'частотный преобразователь',
                'verbose_name_plural': 'Частотные преобразователи',
            },
        ),
        migrations.CreateModel(
            name='ListDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='ListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Участок')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='list_lines.listdepartment', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'участок',
                'verbose_name_plural': 'Участки',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Отдел обслуживания')),
            ],
            options={
                'verbose_name': 'отдел обслуживания',
                'verbose_name_plural': 'Отделы обслуживания',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='SystemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Система')),
                ('line_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='list_lines.listline', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'системы',
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.DeleteModel(
            name='ListВepartment',
        ),
        migrations.AddField(
            model_name='frequencyconverterlist',
            name='line_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.listline', verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='frequencyconverterlist',
            name='maintenance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_lines.maintenancelist', verbose_name='Отдел обслуживания'),
        ),
        migrations.AddField(
            model_name='frequencyconverterlist',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.manufacturerlist'),
        ),
        migrations.AddField(
            model_name='frequencyconverterlist',
            name='system_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='line_type', chained_model_field='line_type', on_delete=django.db.models.deletion.CASCADE, to='list_lines.systemline', verbose_name='Системы'),
        ),
    ]
