# Generated by Django 5.1.1 on 2026-03-30 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0002_listdepartment_delete_listвepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Участок')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.listdepartment')),
            ],
            options={
                'verbose_name': 'учсток',
                'verbose_name_plural': 'Участки',
            },
        ),
    ]
