# Generated by Django 5.1.1 on 2026-04-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0002_frequencyconverterlist_listdepartment_listline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='line_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converter', to='list_lines.listline', verbose_name='Участок'),
        ),
    ]
