# Generated by Django 5.1.1 on 2026-04-28 18:18

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0003_alter_frequencyconverterlist_line_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='is_status_document',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='is_status_spare_part',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='ЗИП'),
        ),
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='line_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.listline', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.manufacturerlist', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='system_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='line_type', chained_model_field='line_type', on_delete=django.db.models.deletion.CASCADE, related_name='converter', to='list_lines.systemline', verbose_name='Системы'),
        ),
    ]
