# Generated by Django 5.1.1 on 2026-04-03 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0003_listline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AlterModelOptions(
            name='listline',
            options={'verbose_name': 'участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.CreateModel(
            name='SystemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Система')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.listline')),
            ],
            options={
                'verbose_name': 'системы',
                'verbose_name_plural': 'Системы',
            },
        ),
    ]
