# Generated by Django 6.0.4 on 2026-05-01 16:36

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0004_alter_frequencyconverterlist_is_status_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'расположение',
                'verbose_name_plural': 'Расположение',
            },
        ),
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_status_document', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Инструкция')),
                ('is_status_spare_part', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='ЗИП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(max_length=100, verbose_name='Оборудование')),
                ('is_status_programm', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Параметры')),
                ('line_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.listline', verbose_name='Участок')),
                ('maintenance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='list_lines.maintenancelist', verbose_name='Отдел обслуживания')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.manufacturerlist', verbose_name='Производитель')),
                ('system_type', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='line_type', chained_model_field='line_type', on_delete=django.db.models.deletion.CASCADE, related_name='system', to='list_lines.systemline', verbose_name='Системы')),
                ('equipment_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='list_lines.equipmenttypelist', verbose_name='Тип оборудования')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='list_lines.location', verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.DeleteModel(
            name='FrequencyConverterList',
        ),
    ]
