# Generated by Django 5.1.1 on 2026-04-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0004_manufacturerlist_alter_listline_options_systemline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyConverterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_status_document', models.BooleanField(default=False, verbose_name='Инструкция')),
                ('is_status_spare_part', models.BooleanField(default=False, verbose_name='ЗИП')),
                ('description', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=100, verbose_name='Частотный преобразователь')),
                ('is_status_programm', models.BooleanField(verbose_name='Параметры')),
                ('department_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.systemline')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_lines.manufacturerlist')),
            ],
            options={
                'verbose_name': 'частотный преобразователь',
                'verbose_name_plural': 'Частотные преобразователи',
            },
        ),
    ]
