# Generated by Django 3.2.16 on 2026-04-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0005_frequencyconverterlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencyconverterlist',
            old_name='department_type',
            new_name='system_type',
        ),
    ]
