# Generated by Django 3.2.16 on 2026-04-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0006_rename_department_type_frequencyconverterlist_system_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listline',
            name='department_type',
        ),
        migrations.RemoveField(
            model_name='systemline',
            name='department_type',
        ),
        migrations.AddField(
            model_name='listline',
            name='line_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list_lines.listdepartment', verbose_name='Участок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemline',
            name='systeml_line_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list_lines.listline', verbose_name='Система'),
            preserve_default=False,
        ),
    ]
