# Generated by Django 3.2.16 on 2026-04-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0009_alter_frequencyconverterlist_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencyconverterlist',
            name='line_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list_lines.listline', verbose_name='Участок'),
            preserve_default=False,
        ),
    ]
