# Generated by Django 3.2.16 on 2026-04-07 17:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0011_alter_frequencyconverterlist_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='system_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='line_type', chained_model_field='line_type', on_delete=django.db.models.deletion.CASCADE, to='list_lines.systemline', verbose_name='Системы'),
        ),
    ]
