# Generated by Django 5.1.1 on 2026-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_lines', '0014_alter_frequencyconverterlist_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencyconverterlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
